name: Run Playwright On GitHub Action
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installing package list
        run: apt list --installed    
      
      # Install Playwright and dependencies
      - name: Installing all necessary packages
        run: |
          pip install playwright beautifulsoup4 feedgenerator requests
          python -m playwright install chromium
      
      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Remove old feed.rss file
        run: rm -f feed.rss
      
      - name: Remove old poke feed.rss file
        run: rm -f pokemon/feed.rss

      - name: Running the Python script with Playwright
        run: python feedgen-playwright.py

      - name: Running the Pokemon Python script
        run: python pokemon/poke-feedgen.py
        
      - name: Commit Changes
        run: |
          git config --global user.name 'Dev7117'
          git config --global user.email 'Dev7117@users.noreply.github.com'
          git add .
          git commit -am "Automated Commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSHPAT2 }}